import { Area } from '../Models/Area';
import { Stronghold } from '../Models/Stronghold';
import { SiteOfPower } from '../Models/SiteOfPower';
import { AreaName } from './AreaNames';
import { AreaType } from '../Models/AreaType';
import { Player } from '../Models/Player';

export const getAreas = () =>  { 
    return {
    FORLINDON: new Area(AreaName.FORLINDON),
    MITHLOND: new SiteOfPower(AreaName.MITHLOND),
    EVENDIM_HILLS: new Stronghold(AreaName.EVENDIM_HILLS),
    TOWER_HILLS: new Area(AreaName.TOWER_HILLS),
    LUNE_VALLEY: new Area(AreaName.LUNE_VALLEY),
    THE_SHIRE: new SiteOfPower(AreaName.THE_SHIRE),
    HARLINDON: new SiteOfPower(AreaName.HARLINDON),
    FORODWAITH: new SiteOfPower(AreaName.FORODWAITH),
    EASTERN_ANGMAR: new SiteOfPower(AreaName.EASTERN_ANGMAR),
    ANGMAR: new Area(AreaName.ANGMAR),
    BORDERLANDS: new Area(AreaName.BORDERLANDS),
    NORTH_DOWNS: new Area(AreaName.NORTH_DOWNS),
    RHUDAUR: new Stronghold(AreaName.RHUDAUR),
    WEATHER_HILLS: new SiteOfPower(AreaName.WEATHER_HILLS),
    FORNOST: new SiteOfPower(AreaName.FORNOST),
    OLD_FOREST: new Area(AreaName.OLD_FOREST),
    BUCKLAND: new Area(AreaName.BUCKLAND),
    SOUTH_DOWNS: new Area(AreaName.SOUTH_DOWNS),
    NORTH_RHUN: new Area(AreaName.NORTH_RHUN),
    WITHERED_HEATH: new Area(AreaName.WITHERED_HEATH),
    ESGAROTH: new SiteOfPower(AreaName.ESGAROTH),
    SOUTH_RHUN: new Area(AreaName.SOUTH_RHUN),
    CARROCK: new Area(AreaName.CARROCK),
    NORTH_MIRKWOOD: new SiteOfPower(AreaName.NORTH_MIRKWOOD),
    ANDUIN_VALLEY: new Area(AreaName.ANDUIN_VALLEY),
    EASTERN_MIRKWOOD: new Area(AreaName.EASTERN_MIRKWOOD),
    SOUTH_MIRKWOOD: new Stronghold(AreaName.SOUTH_MIRKWOOD),
    EREGION: new SiteOfPower(AreaName.EREGION),
    MINHIRIATH: new SiteOfPower(AreaName.MINHIRIATH),
    DUNLAND: new Area(AreaName.DUNLAND),
    ENEDWAITH: new Area(AreaName.ENEDWAITH),
    FANGORN: new Stronghold(AreaName.FANGORN),
    WEST_ROHAN: new Stronghold(AreaName.WEST_ROHAN),
    GAP_OF_ROHAN: new SiteOfPower(AreaName.GAP_OF_ROHAN),
    MORIA: new Stronghold(AreaName.MORIA),
    GLADDEN_FIELDS: new Area(AreaName.GLADDEN_FIELDS),
    LORIEN: new SiteOfPower(AreaName.LORIEN),
    THE_WOLD: new SiteOfPower(AreaName.THE_WOLD),
    EMYN_MUIL: new Area(AreaName.EMYN_MUIL),
    RHUN_HILLS: new Area(AreaName.RHUN_HILLS),
    DEAD_MARSHES: new SiteOfPower(AreaName.DEAD_MARSHES),
    BROWNLANDS: new Area(AreaName.BROWNLANDS),
    DRUWAITH_IAUR: new Area(AreaName.DRUWAITH_IAUR),
    ANDRAST: new Area(AreaName.ANDRAST),
    ANFALAS: new Area(AreaName.ANFALAS),
    VALE_OF_ERECH: new SiteOfPower(AreaName.VALE_OF_ERECH),
    LAMEDON: new Area(AreaName.LAMEDON),
    BELFALAS: new SiteOfPower(AreaName.BELFALAS),
    LEBENNIN: new SiteOfPower(AreaName.LEBENNIN),
    MINAS_TIRITH: new Stronghold(AreaName.MINAS_TIRITH),
    ITHILIEN: new SiteOfPower(AreaName.ITHILIEN),
    SOUTH_ITHILIEN: new Area(AreaName.SOUTH_ITHILIEN),
    UDUN_VALE: new Stronghold(AreaName.UDUN_VALE),
    MOUNT_DOOM: new SiteOfPower(AreaName.MOUNT_DOOM),
    BARAD_DUR: new Stronghold(AreaName.BARAD_DUR),
    GORGOROTH: new Area(AreaName.GORGOROTH),
    MINAS_MORGUL: new Stronghold(AreaName.MINAS_MORGUL),
    NURN: new Area(AreaName.NURN),
    HARONDOR: new Area(AreaName.HARONDOR),
    UMBAR: new Stronghold(AreaName.UMBAR),
    DEEP_HARAD: new Area(AreaName.DEEP_HARAD),
    HARAD: new Area(AreaName.HARAD),
    NEAR_HARAD: new Area(AreaName.NEAR_HARAD),
    KHAND: new SiteOfPower(AreaName.KHAND),
    }
}