from game_logic.models.Area import Area
from game_logic.models.SiteOfPower import SiteOfPower
from game_logic.models.Stronghold import Stronghold
from typing import Dict

# Needs to return areas via a function call, as otherwise 
# the same Area class instances are reused for all games
def get_areas() -> Dict[str, Area]:
    areas = {
        "FORLINDON": Area("FORLINDON"),
        "MITHLOND": SiteOfPower("MITHLOND"),
        "EVENDIM_HILLS": Stronghold("EVENDIM_HILLS"),
        "TOWER_HILLS": Area("TOWER_HILLS"),
        "LUNE_VALLEY": Area("LUNE_VALLEY"),
        "THE_SHIRE": SiteOfPower("THE_SHIRE"),
        "HARLINDON": SiteOfPower("HARLINDON"),
        "FORODWAITH": SiteOfPower("FORODWAITH"),
        "EASTERN_ANGMAR": SiteOfPower("EASTERN_ANGMAR"),
        "ANGMAR": Area("ANGMAR"),
        "BORDERLANDS": Area("BORDERLANDS"),
        "NORTH_DOWNS": Area("NORTH_DOWNS"),
        "RHUDAUR": Stronghold("RHUDAUR"),
        "WEATHER_HILLS": SiteOfPower("WEATHER_HILLS"),
        "FORNOST": SiteOfPower("FORNOST"),
        "OLD_FOREST": Area("OLD_FOREST"),
        "BUCKLAND": Area("BUCKLAND"),
        "SOUTH_DOWNS": Area("SOUTH_DOWNS"),
        "NORTH_RHUN": Area("NORTH_RHUN"),
        "WITHERED_HEATH": Area("WITHERED_HEATH"),
        "ESGAROTH": SiteOfPower("ESGAROTH"),
        "SOUTH_RHUN": Area("SOUTH_RHUN"),
        "CARROCK": Area("CARROCK"),
        "NORTH_MIRKWOOD": SiteOfPower("NORTH_MIRKWOOD"),
        "ANDUIN_VALLEY": Area("ANDUIN_VALLEY"),
        "EASTERN_MIRKWOOD": Area("EASTERN_MIRKWOOD"),
        "SOUTH_MIRKWOOD": Area("SOUTH_MIRKWOOD"),
        "EREGION": SiteOfPower("EREGION"),
        "MINHIRIATH": SiteOfPower("MINHIRIATH"),
        "DUNLAND": Area("DUNLAND"),
        "ENEDWAITH": Area("ENEDWAITH"),
        "FANGORN": Stronghold("FANGORN"),
        "WEST_ROHAN": Stronghold("WEST_ROHAN"),
        "GAP_OF_ROHAN": SiteOfPower("GAP_OF_ROHAN"),
        "MORIA": Stronghold("MORIA"),
        "GLADDEN_FIELDS": Area("GLADDEN_FIELDS"),
        "LORIEN": SiteOfPower("LORIEN"),
        "THE_WOLD": SiteOfPower("THE_WOLD"),
        "EMYN_MUIL": Area("EMYN_MUIL"),
        "RHUN_HILLS": Area("RHUN_HILLS"),
        "DEAD_MARSHES": Area("DEAD_MARSHES"),
        "BROWNLANDS": Area("BROWNLANDS"),
        "DRUWAITH_IAUR": Area("DRUWAITH_IAUR"),
        "ANDRAST": Area("ANDRAST"),
        "ANFALAS": Area("ANFALAS"),
        "VALE_OF_ERECH": SiteOfPower("VALE_OF_ERECH"),
        "LAMEDON": Area("LAMEDON"),
        "BELFALAS": SiteOfPower("BELFALAS"),
        "LEBENNIN": SiteOfPower("LEBENNIN"),
        "MINAS_TIRITH": Stronghold("MINAS_TIRITH"),
        "ITHILIEN": SiteOfPower("ITHILIEN"),
        "SOUTH_ITHILIEN": Area("SOUTH_ITHILIEN"),
        "UDUN_VALE": Stronghold("UDUN_VALE"),
        "MOUNT_DOOM": SiteOfPower("MOUNT_DOOM"),
        "BARAD_DUR": Stronghold("BARAD_DUR"),
        "GORGOROTH": Area("GORGOROTH"),
        "MINAS_MORGUL": Stronghold("MINAS_MORGUL"),
        "NURN": Area("NURN"),
        "HARONDOR": Area("HARONDOR"),
        "UMBAR": Stronghold("UMBAR"),
        "DEEP_HARAD": Area("DEEP_HARAD"),
        "HARAD": Area("HARAD"),
        "NEAR_HARAD": Area("NEAR_HARAD"),
        "KHAND": SiteOfPower("KHAND")
    }
    
    return areas
