import { Area } from '../Models/Area';
import { Stronghold } from '../Models/Stronghold';
import { SiteOfPower } from '../Models/SiteOfPower';
import { AreaName } from './AreaNames';
import * as  Adjacencies from './AreaAdjacencies';

export const Areas = {
    FORLINDON: new Area(AreaName.FORLINDON, Adjacencies.FORLINDON),
    MITHLOND: new SiteOfPower(AreaName.MITHLOND, Adjacencies.MITHLOND),
    EVENDIM_HILLS: new Stronghold(AreaName.EVENDIM_HILLS, Adjacencies.EVENDIM_HILLS),
    TOWER_HILLS: new Area(AreaName.TOWER_HILLS, Adjacencies.TOWER_HILLS),
    LUNE_VALLEY: new Area(AreaName.LUNE_VALLEY, Adjacencies.LUNE_VALLEY),
    THE_SHIRE: new SiteOfPower(AreaName.THE_SHIRE, Adjacencies.THE_SHIRE),
    HARLINDON: new SiteOfPower(AreaName.HARLINDON, Adjacencies.HARLINDON),
    FORODWAITH: new SiteOfPower(AreaName.FORODWAITH, Adjacencies.FORODWAITH),
    EASTERN_ANGMAR: new SiteOfPower(AreaName.EASTERN_ANGMAR, Adjacencies.EASTERN_ANGMAR),
    ANGMAR: new Area(AreaName.ANGMAR, Adjacencies.ANGMAR),
    BORDERLANDS: new Area(AreaName.BORDERLANDS, Adjacencies.BORDERLANDS),
    NORTH_DOWNS: new Area(AreaName.NORTH_DOWNS, Adjacencies.NORTH_DOWNS),
    RHUDAUR: new Stronghold(AreaName.RHUDAUR, Adjacencies.RHUDAUR),
    WEATHER_HILLS: new SiteOfPower(AreaName.WEATHER_HILLS, Adjacencies.WEATHER_HILLS),
    FORNOST: new SiteOfPower(AreaName.FORNOST, Adjacencies.FORNOST),
    OLD_FOREST: new Area(AreaName.OLD_FOREST, Adjacencies.OLD_FOREST),
    BUCKLAND: new Area(AreaName.BUCKLAND, Adjacencies.BUCKLAND),
    SOUTH_DOWNS: new Area(AreaName.SOUTH_DOWNS, Adjacencies.SOUTH_DOWNS),
    NORTH_RHUN: new Area(AreaName.NORTH_RHUN, Adjacencies.NORTH_RHUN),
    WITHERED_HEATH: new Area(AreaName.WITHERED_HEATH, Adjacencies.WITHERED_HEATH),
    ESGAROTH: new SiteOfPower(AreaName.ESGAROTH, Adjacencies.ESGAROTH),
    SOUTH_RHUN: new Area(AreaName.SOUTH_RHUN, Adjacencies.SOUTH_RHUN),
    CARROCK: new Area(AreaName.CARROCK, Adjacencies.CARROCK),
    NORTH_MIRKWOOD: new SiteOfPower(AreaName.NORTH_MIRKWOOD, Adjacencies.NORTH_MIRKWOOD),
    ANDUIN_VALLEY: new Area(AreaName.ANDUIN_VALLEY, Adjacencies.ANDUIN_VALLEY),
    EASTERN_MIRKWOOD: new Area(AreaName.EASTERN_MIRKWOOD, Adjacencies.EASTERN_MIRKWOOD),
    SOUTH_MIRKWOOD: new Stronghold(AreaName.SOUTH_MIRKWOOD, Adjacencies.SOUTH_MIRKWOOD),
    EREGION: new SiteOfPower(AreaName.EREGION, Adjacencies.EREGION),
    MINHIRIATH: new SiteOfPower(AreaName.MINHIRIATH, Adjacencies.MINHIRIATH),
    DUNLAND: new Area(AreaName.DUNLAND, Adjacencies.DUNLAND),
    ENEDWAITH: new Area(AreaName.ENEDWAITH, Adjacencies.ENEDWAITH),
    FANGORN: new Stronghold(AreaName.FANGORN, Adjacencies.FANGORN),
    WEST_ROHAN: new Stronghold(AreaName.WEST_ROHAN, Adjacencies.WEST_ROHAN),
    GAP_OF_ROHAN: new SiteOfPower(AreaName.GAP_OF_ROHAN, Adjacencies.GAP_OF_ROHAN),
    MORIA: new Stronghold(AreaName.MORIA, Adjacencies.MORIA),
    GLADDEN_FIELDS: new Area(AreaName.GLADDEN_FIELDS, Adjacencies.GLADDEN_FIELDS),
    LORIEN: new SiteOfPower(AreaName.LORIEN, Adjacencies.LORIEN),
    THE_WOLD: new SiteOfPower(AreaName.THE_WOLD, Adjacencies.THE_WOLD),
    EMYN_MUIL: new Area(AreaName.EMYN_MUIL, Adjacencies.EMYN_MUIL),
    RHUN_HILLS: new Area(AreaName.RHUN_HILLS, Adjacencies.RHUN_HILLS),
    DEAD_MARSHES: new SiteOfPower(AreaName.DEAD_MARSHES, Adjacencies.DEAD_MARSHES),
    BROWNLANDS: new Area(AreaName.BROWNLANDS, Adjacencies.BROWNLANDS),
    DRUWAITH_IAUR: new Area(AreaName.DRUWAITH_IAUR, Adjacencies.DRUWAITH_IAUR),
    ANDRAST: new Area(AreaName.ANDRAST, Adjacencies.ANDRAST),
    ANFALAS: new Area(AreaName.ANFALAS, Adjacencies.ANFALAS),
    VALE_OF_ERECH: new SiteOfPower(AreaName.VALE_OF_ERECH, Adjacencies.VALE_OF_ERECH),
    LAMEDON: new Area(AreaName.LAMEDON, Adjacencies.LAMEDON),
    BELFALAS: new SiteOfPower(AreaName.BELFALAS, Adjacencies.BELFALAS),
    LEBENNIN: new SiteOfPower(AreaName.LEBENNIN, Adjacencies.LEBENNIN),
    MINAS_TIRITH: new Stronghold(AreaName.MINAS_TIRITH, Adjacencies.MINAS_TIRITH),
    ITHILIEN: new SiteOfPower(AreaName.ITHILIEN, Adjacencies.ITHILIEN),
    SOUTH_ITHILIEN: new Area(AreaName.SOUTH_ITHILIEN, Adjacencies.SOUTH_ITHILIEN),
    UDUN_VALE: new Stronghold(AreaName.UDUN_VALE, Adjacencies.UDUN_VALE),
    MOUNT_DOOM: new SiteOfPower(AreaName.MOUNT_DOOM, Adjacencies.MOUNT_DOOM),
    BARAD_DUR: new Stronghold(AreaName.BARAD_DUR, Adjacencies.BARAD_DUR),
    GORGOROTH: new Area(AreaName.GORGOROTH, Adjacencies.GORGOROTH),
    MINAS_MORGUL: new Stronghold(AreaName.MINAS_MORGUL, Adjacencies.MINAS_MORGUL),
    NURN: new Area(AreaName.NURN, Adjacencies.NURN),
    HARONDOR: new Area(AreaName.HARONDOR, Adjacencies.HARONDOR),
    UMBAR: new Stronghold(AreaName.UMBAR, Adjacencies.UMBAR),
    DEEP_HARAD: new Area(AreaName.DEEP_HARAD, Adjacencies.DEEP_HARAD),
    HARAD: new Area(AreaName.HARAD, Adjacencies.HARAD),
    NEAR_HARAD: new Area(AreaName.NEAR_HARAD, Adjacencies.NEAR_HARAD),
    KHAND: new SiteOfPower(AreaName.KHAND, Adjacencies.KHAND),
}